version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 # Update to Python 3.10
    commands:
      - echo "Installing system dependencies"
      - yum update -y
      - yum install -y mysql-devel
      
  pre_build:
    commands:
      - echo "Upgrading pip"
      - pip install --upgrade pip
      - echo "Installing project dependencies"
      - pip install -r LeaveTracking/requirements.txt

  build:
    commands:
      - echo "Running migrations"
      - python LeaveTracking/manage.py makemigrations
      - python LeaveTracking/manage.py migrate

  post_build:
    commands:
      - echo "Running tests"
      - python LeaveTracking/manage.py test --noinput --verbosity 2 Leave.tests
      - if [ $? -ne 0 ]; then echo "Test failure detected. Stopping build." && exit 1; fi

artifacts:
  files: '**/*'
