# Generated by Django 3.2 on 2021-04-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('Primary_Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leave_Type', models.CharField(choices=[('Sick-Leave', 'Sick-Leave'), ('Casual-Leave', 'Casual-Leave'), ('Personal-Leave', 'Personal-Leave')], default='Sick-Leave', max_length=20)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'december')], max_length=10)),
                ('Year', models.CharField(max_length=4)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Reason', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=10)),
                ('Employee_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Leave.employee_detail')),
            ],
        ),
    ]
