# Generated by Django 3.2 on 2023-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0002_alter_leave_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='Employee_Name',
            field=models.CharField(max_length=30),
        ),
    ]
